name: LiteParkour
version: '1.0-SNAPSHOT'
main: me.liamgiraldo.liteParkour.LiteParkour
api-version: '1.8'
author: Liam Giraldo
description: A simple parkour plugin for Minecraft servers.
commands:
  parkour:
      description: Main command for the LiteParkour plugin.
      usage: /parkour <subcommand> [args]
      aliases:
      - pk
      - lpk
      - litepk
      - liteparkour
      - parkours
permissions:
  parkour.command:
    description: Permission to use the main parkour command.
    default: op
